- id: pre-commit-check
  name: pre-commit-check
  description: 'pre-commit-checker: Check for outdated requirements'
  entry: pip_version
  language: python
  # minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
